export default {
  component: 'VPanel',
  label: '面板',
  icon: 'VPanel',
  type: 'box',
  propValue: {},
  style: {
    width: 400,
    height: 400,
    fixedWidth: '100%',
    fixedHeight: '100%',
    backgroundColor: '#fff',
    display: 'block',
    borderWidth: 0,
    borderColor: '#ffffff',
    borderStyle: 'solid',
    fixedWidth: '',
    fixedHeight: '',
  },
  childs: [],
  position: 'top',
}