// 公共样式
export const commonStyle = {
    rotate: 0,
    opacity: 1,
};

export const commonAttr = {
    animations: [],
    events: {},
    dataBinds: {},
    actionBinds: {},
    groupStyle: {}, // 当一个组件成为 Group 的子组件时使用
    isLock: false, // 是否锁定组件
    collapseName: '', // 编辑组件时记录当前使用的是哪个折叠面板，再次回来时恢复上次打开的折叠面板，优化用户体验
    linkage: {
        duration: 0,
        data: [
            // 组件联动
            {
                id: '',
                label: '',
                event: '',
                style: [{ key: '', value: '' }],
                events: [{ name: '' }],
            },
        ],
    },
};

// 编辑器左侧组件列表
const list = [
    // HTML
    {
        component: 'VHtml',
        label: 'HTML',
        propValue: {
            value: ''
        },
        icon: 'VHtml',
        type: 'common',
        style: {
            width: 300,
            height: 300,
            borderWidth: 1,
            borderColor: '#ccc',
            borderRadius: '',
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
    },
    // 文字
    {
        component: 'VText',
        label: '文字',
        propValue: {
            value: '文字'
        },
        icon: 'wenben',
        type: 'common',
        style: {
            width: 200,
            height: 28,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
        },
    },
    // 按钮
    {
        component: 'VButton',
        label: '按钮',
        propValue: {
            value: '按钮'
        },
        icon: 'button',
        type: 'common',
        style: {
            width: 100,
            height: 34,
            borderWidth: 1,
            borderColor: '',
            borderRadius: '',
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
    },
    // 单选按钮组
    {
        component: 'VRadio',
        label: '单选按钮组',
        propValue: {
            key: '',
            options: [],
            label: '字段名',
            isBtn: false,
        },
        icon: 'VRadio',
        type: 'common',
        style: {
            width: 200,
            height: 34,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
        eventOptions: [{ label: '数据改变', value: 'updateValue' }],
    },
    // 多选框组
    {
        component: 'VCheckBox',
        label: '多选框组',
        propValue: {
            key: '',
            options: [],
            label: '字段名',
            isBtn: false,
            value: [],
        },
        icon: 'VCheckBox',
        type: 'common',
        style: {
            width: 200,
            height: 34,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
        eventOptions: [{ label: '数据改变', value: 'updateValue' }],
    },
    // 文本域
    {
        component: 'VTextArea',
        label: '文本域',
        propValue: {
            key: '',
            options: [],
            label: '字段名',
        },
        icon: 'VTextArea',
        type: 'common',
        style: {
            width: 200,
            height: 54,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
        eventOptions: [{ label: '数据改变', value: 'updateValue' }],
    },
    // 微调器
    {
        component: 'VInputNumber',
        label: '微调器',
        propValue: {
            key: '',
            options: [],
            label: '字段名',
            precision: 0,
            step: 1,
            max: 100,
            min: 0,
        },
        icon: 'VInputNumber',
        type: 'common',
        style: {
            width: 200,
            height: 34,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
        eventOptions: [{ label: '数据改变', value: 'updateValue' }],
    },
    // 日期选择器
    {
        component: 'VDate',
        label: '日期选择器',
        propValue: {
            key: '',
            options: [],
            label: '字段名',
            valueFormat: 'date',
        },
        icon: 'VDate',
        type: 'common',
        style: {
            width: 200,
            height: 54,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
        eventOptions: [{ label: '数据改变', value: 'updateValue' }],
    },
    // 滑块
    {
        component: 'VSlide',
        label: '滑块',
        propValue: {
            key: '',
            options: [],
            label: '字段名',
            step: 1,
            max: 100,
            min: 0,
        },
        icon: 'VSlide',
        type: 'common',
        style: {
            width: 200,
            height: 54,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
        eventOptions: [{ label: '数据改变', value: 'updateValue' }],
    },
    // 图片
    {
        component: 'Picture',
        label: '图片',
        icon: 'tupian',
        type: 'common',
        propValue: {
            url: () => require('@/assets/title.jpg'),
            flip: {
                horizontal: false,
                vertical: false,
            },
            isUpload: true,
        },
        request: {
            method: 'post',
            data: [],
            url: '/mohub/common/upload',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 300,
            height: 200,
            borderRadius: '',
            borderWidth: 1,
            borderColor: '',
        },
    },
    {
        component: 'TreeList',
        label: '树形',
        icon: 'tree',
        type: 'common',
        propValue: {
            isShowCheck: false,
            props: {
                label: 'label',
                children: 'children',
                isLeaf: 'leaf',
            },
            isLazy: false,
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 300,
            height: 450,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        eventOptions: [
            { label: '节点点击', value: 'handleNodeClick' },
            { label: '节点选中', value: 'handleCheckChange' },
        ],
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }],
    },
    // 矩形
    // {
    //     component: 'RectShape',
    //     label: '矩形',
    //     propValue: '&nbsp;',
    //     icon: 'juxing',
    //     style: {
    //         width: 200,
    //         height: 200,
    //         fontSize: '',
    //         fontWeight: 400,
    //         lineHeight: '',
    //         letterSpacing: 0,
    //         textAlign: 'center',
    //         color: '',
    //         borderColor: '#000',
    //         borderWidth: 1,
    //         backgroundColor: '',
    //         borderStyle: 'solid',
    //         borderRadius: '',
    //         verticalAlign: 'middle',
    //     },
    // },
    // // 直线
    // {
    //     component: 'LineShape',
    //     label: '直线',
    //     propValue: '',
    //     icon: 'zhixian',
    //     style: {
    //         width: 200,
    //         height: 2,
    //         backgroundColor: '#000',
    //     },
    // },
    // // 圆形
    // {
    //     component: 'CircleShape',
    //     label: '圆形',
    //     propValue: '&nbsp;',
    //     icon: '24gl-circle',
    //     style: {
    //         width: 200,
    //         height: 200,
    //         fontSize: '',
    //         fontWeight: 400,
    //         lineHeight: '',
    //         letterSpacing: 0,
    //         textAlign: 'center',
    //         color: '',
    //         borderColor: '#000',
    //         borderWidth: 1,
    //         backgroundColor: '',
    //         borderStyle: 'solid',
    //         borderRadius: '',
    //         verticalAlign: 'middle',
    //     },
    // },
    // // 星形
    // {
    //     component: 'SVGStar',
    //     label: '星形',
    //     icon: 'kongwujiaoxing',
    //     propValue: '',
    //     style: {
    //         width: 80,
    //         height: 80,
    //         fontSize: '',
    //         fontWeight: 400,
    //         lineHeight: '',
    //         letterSpacing: 0,
    //         textAlign: 'center',
    //         color: '',
    //         borderColor: '#000',
    //         backgroundColor: 'rgba(255, 255, 255, 1)',
    //     },
    // },
    // // 三角形
    // {
    //     component: 'SVGTriangle',
    //     label: '三角形',
    //     icon: 'xingzhuang-sanjiaoxing',
    //     propValue: '',
    //     style: {
    //         width: 80,
    //         height: 80,
    //         fontSize: '',
    //         fontWeight: 400,
    //         lineHeight: '',
    //         letterSpacing: 0,
    //         textAlign: 'center',
    //         color: '',
    //         borderColor: '#000',
    //         backgroundColor: 'rgba(255, 255, 255, 1)',
    //     },
    // },
    // 表格
    {
        component: 'VTable',
        label: '表格',
        icon: 'table',
        type: 'common',
        propValue: {
            columns: [
                {
                    label: '姓名',
                    field: 'name',
                },
                {
                    label: '日期',
                    field: 'date',
                },
                {
                    label: '地址',
                    field: 'address',
                },
            ],
            data: [
                {
                    date: '2016-05',
                    name: '王小虎',
                    address: '上海市',
                },
                {
                    date: '2016-05',
                    name: '王小虎',
                    address: '上海市',
                },
                {
                    date: '2016-05',
                    name: '王小虎',
                    address: '上海市',
                },
            ],
            stripe: true,
            border: true,
            thBold: true,
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 600,
            height: 200,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'center',
            color: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
    },
    {
        component: 'Tabs',
        label: '标签页',
        icon: 'tabs',
        type: 'box',
        propValue: [],
        style: {
            width: 400,
            height: 200,
            display: 'block',
        },
        childs: [],
        tabs: [],
        position: 'top',
        eventOptions: [{ label: 'tab切换', value: 'updateValue' }],
    },
    {
        component: 'GridLayout',
        label: '网格',
        icon: 'grid',
        type: 'box',
        propValue: [],
        style: {
            width: 400,
            height: 400,
            backgroundColor: '#fff',
            display: 'block',
        },
        childs: [],
        items: [],
        cols: 3,
        rows: 3,
    },
    {
        component: 'VPanel',
        label: '面板',
        icon: 'VPanel',
        type: 'box',
        propValue: [],
        style: {
            width: 400,
            height: 400,
            backgroundColor: '#fff',
            display: 'block',
        },
        childs: [],
        position: 'top',
    },
    {
        component: 'TyCharts',
        label: '曲线/柱状图',
        icon: 'chart-line',
        type: 'Ty',
        propValue: {
            props: {
                type: 'line',
            },
            showPlay: true,
            title: '',
            titleColor: '#333',
            titleSize: 18,
            titleAlign: 'left',
            autoPlay: false,
            circulate: false,
            autoPlayTime: 100,
        },
        request: {
            method: 'POST',
            data: [],
            url: 'https://mohub.net/alchemy/simulationResult/queryCurveOperationResult',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 600,
            height: 300,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }, { label: '参数设置', value: 'setParams' }],
        eventOptions: [{ label: '坐标指示', value: 'updateAxisPointer' }],
    },
    {
        component: 'Radar',
        label: '雷达图',
        icon: 'leidatu',
        type: 'Ty',
        propValue: {
            title: '',
            titleColor: '#333',
            titleSize: 18,
            titleAlign: 'left',
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 600,
            height: 300,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }],
    },
    {
        component: 'Pie',
        label: '饼图',
        icon: 'bingtu',
        type: 'Ty',
        propValue: {
            title: '',
            titleColor: '#333',
            titleSize: 18,
            titleAlign: 'left',
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 600,
            height: 300,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }],
    },
    {
        component: 'Gauge',
        label: '仪表盘',
        icon: 'yibiaopan',
        type: 'Ty',
        propValue: {
            isShowProgress: false,
            isShowTick: false,
            valueUnit: 'km/h',
            labelFontSize: 14,
            valueFontSize: 30,
            startAngle: 225,
            endAngle: -45,
            min: 0,
            max: 100,
            floatUnit: 2,
            title: '',
            titleColor: '#333',
            titleSize: 18,
            titleAlign: 'left',
            labelColor: '#333',
            valueColor: '#333',
            warningValue: 0,
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 600,
            height: 300,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }],
    },
    {
        component: 'SvgViewer',
        label: '模型画布',
        icon: 'model',
        type: 'Ty',
        propValue: {},
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 600,
            height: 600,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }],
        eventOptions: [{ label: '节点选中', value: 'componentChange' }],
    },
    {
        component: 'ModelAttributes',
        label: '开始仿真',
        icon: 'shuxing',
        type: 'Ty',
        propValue: {
            showSetting: true,
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 86,
            height: 35,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }, { label: '参数刷新', value: 'updateParams' }, { label: '参数设置', value: 'setParams' }],
        eventOptions: [{ label: '仿真成功', value: 'simulateCompleted' }],
    },
    {
        component: 'TyModelParams',
        label: '组件参数',
        icon: 'yewucanshu',
        type: 'Ty',
        propValue: {},
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 300,
            height: 450,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }],
        eventOptions: [{ label: '参数改变', value: 'updateSvgViewer' }],
    },
    {
        component: 'ModelUser',
        label: '用户模型',
        icon: 'tree',
        type: 'Ty',
        propValue: {},
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 300,
            height: 450,
            fontSize: '',
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        eventOptions: [{ label: '节点点击', value: 'updateModelTab' }],
    },
    // 标题
    {
        component: 'RTitle',
        label: '标题',
        propValue: { text: '标题' },
        icon: 'zitibiaoti',
        type: 'report',
        style: {
            width: '100%',
            height: 45,
            fontSize: 30,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'center',
            color: '#3C7DC0',
        },
    },
    // 章节
    {
        component: 'Section',
        label: '章节',
        propValue: { text: '章节名' },
        icon: 'zidingyizhangjie',
        type: 'report',
        style: {
            width: '100%',
            height: 400,
            fontSize: 24,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 段落
    {
        component: 'Paragraph',
        label: '段落',
        propValue: { text: '段落...' },
        icon: 'duanla',
        type: 'report',
        style: {
            width: '100%',
            height: 100,
            fontSize: 16,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#000',
        },
    },
    // 模型
    {
        component: 'ModelList',
        label: '模型列表',
        propValue: { text: '章节名', modelList: { list: [] } },
        icon: 'zidingyizhangjie',
        type: 'report',
        style: {
            width: '100%',
            height: 400,
            fontSize: 24,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 模型名称
    {
        component: 'ModelName',
        label: '模型名称',
        propValue: { text: '模型名称' },
        icon: 'mingcheng',
        type: 'report',
        style: {
            width: '100%',
            height: 100,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 模型图形
    {
        component: 'ModelSnapshot',
        label: '模型图形',
        propValue: { text: '模型图形' },
        icon: 'model',
        type: 'report',
        style: {
            width: '100%',
            height: 250,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 文档说明
    {
        component: 'ModelDocument',
        label: '文档说明',
        propValue: { text: '文档说明' },
        icon: 'wendang',
        type: 'report',
        style: {
            width: '100%',
            height: 250,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 参数表格
    {
        component: 'ModelParameterTable',
        label: '参数表格',
        propValue: { text: '参数表格' },
        icon: 'table',
        type: 'report',
        style: {
            width: '100%',
            height: 250,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 仿真
    {
        component: 'SimulationList',
        label: '仿真列表',
        propValue: { text: '章节名', SimulationList: { list: [] } },
        icon: 'zidingyizhangjie',
        type: 'report',
        style: {
            width: '100%',
            height: 400,
            fontSize: 24,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 仿真参数
    {
        component: 'SimulationParameter',
        label: '仿真参数',
        propValue: { text: '仿真参数' },
        icon: 'yewucanshu',
        type: 'report',
        style: {
            width: '100%',
            height: 250,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 仿真设置
    {
        component: 'SimulationSettings',
        label: '仿真设置',
        propValue: { text: '仿真设置' },
        icon: 'shuxing',
        type: 'report',
        style: {
            width: '100%',
            height: 250,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 仿真结果
    {
        component: 'SimulationResult',
        label: '仿真结果',
        propValue: { text: '仿真结果' },
        icon: 'a-gongkaijieguo',
        type: 'report',
        style: {
            width: '100%',
            height: 250,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 变量表格
    {
        component: 'SimulationVariable',
        label: '变量表格',
        propValue: { text: '变量表格' },
        icon: 'table',
        type: 'report',
        style: {
            width: '100%',
            height: 250,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 变量曲线
    {
        component: 'SimulationVariablePlot',
        label: '变量曲线',
        propValue: { text: '变量曲线' },
        icon: 'chart-line',
        type: 'report',
        style: {
            width: '100%',
            height: 250,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    // 变量曲线
    {
        component: 'SimulationTime',
        label: '仿真用时',
        propValue: { text: '仿真用时' },
        icon: 'changyong_shijian',
        type: 'report',
        style: {
            width: '100%',
            height: 250,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    {
        component: 'SelectModel',
        label: '选择模型',
        propValue: '',
        icon: 'model',
        type: 'Ty',
        style: {
            width: '100%',
            height: 70,
            fontSize: 20,
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: 'left',
            color: '#3C7DC0',
        },
    },
    {
        component: 'Lamp',
        label: '灯泡',
        icon: 'lamp',
        type: 'Ty',
        propValue: {
            title: '',
            titleColor: '#333',
            titleSize: 18,
            titleAlign: 'left',
            warningValue: 0,
            warningColor: 'red',
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 50,
            height: 50,
            fontSize: 50,
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }],
    },
    {
        component: 'Tube',
        label: '长方形',
        icon: 'tx-fill',
        type: 'Ty',
        propValue: {
            title: '',
            titleColor: '#333',
            titleSize: 18,
            titleAlign: 'left',
            warningValue: 0,
            warningColor: 'red',
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 100,
            height: 25,
            fontSize: 16,
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(0, 0, 0, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }, { label: '状态高亮', value: 'hightlight' }],
    },
    {
        component: 'ModelInput',
        label: '模型输入',
        icon: 'modelInput',
        type: 'Ty',
        propValue: {
            setting: [],
            value: {},
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 250,
            height: 550,
            fontSize: 16,
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        eventOptions: [{ label: '数据改变', value: 'updateValue' }],
    },
    {
        component: 'ModelOutput',
        label: '模型输出',
        icon: 'modelOutput',
        type: 'Ty',
        propValue: {
            setting: [],
            numberSetting: [],
            value: {},
        },
        request: {
            method: 'GET',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 200,
            height: 550,
            fontSize: 16,
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }],
        eventOptions: [{ label: '数据改变', value: 'updateValue' }],
    },
    {
        component: 'Animation',
        label: '三维动画',
        icon: 'a-3D',
        type: 'Ty',
        propValue: {
            setting: [],
            numberSetting: [],
            value: {},
        },
        request: {
            method: 'POST',
            data: [],
            url: '',
            series: false,
            time: 1000,
            paramType: '', // string object array
            requestCount: 0, // 请求次数限制，0 为无限
        },
        style: {
            width: 550,
            height: 550,
            fontSize: 16,
            fontWeight: 400,
            textAlign: 'left',
            color: '',
            borderWidth: 1,
            borderColor: '',
            backgroundColor: 'rgba(255, 255, 255, 1)',
        },
        handlerOptions: [{ label: '数据刷新', value: 'updateData' }, { label: '播放', value: 'play' }, { label: '暂停', value: 'pause' }, { label: '重置', value: 'reset' }],
    },
];

// 编辑器左侧组件列表
const newList = [
    // HTML
    {
        component: 'VHtml',
        label: 'HTML',
        propValue: {
            value: ''
        },
        icon: 'VHtml',
        type: 'common',
        style: {
            width: 300,
            height: 300,
            borderWidth: 1,
            borderColor: '#ccc',
            borderRadius: '',
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
    },
    // 文字
    {
        component: 'VText',
        label: '文字',
        propValue: {
            value: '文字'
        },
        icon: 'wenben',
        type: 'common',
        style: {
            width: 200,
            height: 28,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
        },
    },
    // 按钮
    {
        component: 'VButton',
        label: '按钮',
        propValue: {
            value: '按钮'
        },
        icon: 'button',
        type: 'common',
        style: {
            width: 100,
            height: 34,
            borderWidth: 1,
            borderColor: '',
            borderRadius: '',
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
        actionBinds: {
            click: ''
        }
    },
    // 输入框
    {
        component: 'VInput',
        label: '输入框',
        propValue: {
            value: '',
            label: '字段名',
        },
        icon: 'input',
        type: 'common',
        style: {
            width: 200,
            height: 34,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        },
        eventOptions: [{ label: '数据改变', value: 'updateValue' }],
    },
    // 下拉框
    {
        component: 'VSelect',
        label: '下拉框',
        propValue: {
            options: [],
            value: '',
            label: '字段名',
        },
        icon: 'select',
        type: 'common',
        style: {
            width: 200,
            height: 34,
            fontSize: '',
            fontWeight: 400,
            lineHeight: '',
            letterSpacing: 0,
            textAlign: '',
            color: '',
            backgroundColor: '',
        }
    },
];

// 把组件数据重新分配定义
for (let i = 0, len = newList.length; i < len; i++) {
    const item = newList[i];
    item.style = { ...commonStyle, ...item.style };
    newList[i] = { ...commonAttr, ...item };
}

export default newList;
